[package]
name = "php_oxc_minifier"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ext-php-rs = "0.12.0"
oxc = { version = "0.48.1", features = ["codegen", "minifier"] }
